apiVersion: apps/v1
kind: Deployment
metadata:
  name: ppdt-client-deploy
  labels:
    app: ppdt-client-deploy
    role: client
spec:
  replicas: 1
  selector:
    matchLabels:
      pod: ppdt-client-deploy
  template:
    metadata:
      labels:
        pod: ppdt-client-deploy
    spec:
      containers:
        - name: ppdt-client-deploy
          image: andrewquijano92/ppdt
          ports:
            - containerPort: 9000
          env:
            - name: TREE_ROLE
              value: "CLIENT"

            - name: PRECISION
              value: "2"

            - name: PORT_NUM
              value: "9000"

            - name: LEVEL_SITE_DOMAINS
              value: "ppdt-level-site-01-service,ppdt-level-site-02-service,ppdt-level-site-03-service,ppdt-level-site-04-service,ppdt-level-site-05-service,ppdt-level-site-06-service,ppdt-level-site-07-service,ppdt-level-site-08-service,ppdt-level-site-09-service,ppdt-level-site-10-service"

            - name: PPDT_KEY_SIZE
              value: "2048"

            - name: SERVER
              value: "ppdt-server-service"

            - name: GRADLE_USER_HOME
              value: "gradle_user_home"
